CREATE PROCEDURE LONDON_QUERY @AREA char(15),@COM FLOAT(10)
As
SELECT * 
FROM AGENTS
WHERE WORKING_AREA = @AREA AND COMMISSION=@COM;
Go

Exec LONDON_QUERY @AREA = 'LONDON',@COM='0.15';
Exec LONDON_QUERY @AREA = 'Banglore',@COM='0.15';
Exec LONDON_QUERY @AREA = 'Chennai',@COM='0.14';