CREATE TABLE 
BANK_ACCOUNT
(
CustomerId INT PRIMARY KEY IDENTITY,
CustomerName VARCHAR(200),
Balance DECIMAL(10,2),
Debit Float,
Credit Float
);

INSERT into BANK_ACCOUNT Values('Himanshu',10000,10000,0);
INSERT into BANK_ACCOUNT Values('Rutuja',10000,10000,0);
INSERT into BANK_ACCOUNT Values('Nikita',10000,10000,0);


CREATE TABLE TRANSACTIONS
(
TransactionId INT PRIMARY KEY IDENTITY(1000,23),
CustomerID INT FOREIGN KEY REFERENCES BANK_ACCOUNT(CustomerId),
TransactionTime DATE,
TransactionAmt DEcimal(10,2)
);


INSERT INTO TRANSACTIONS VALUES(1,CURRENT_TIMESTAMP,1200);
INSERT INTO TRANSACTIONS VALUES(2,CURRENT_TIMESTAMP,1500);
INSERT INTO TRANSACTIONS VALUES(3,CURRENT_TIMESTAMP,1800)
INSERT INTO TRANSACTIONS VALUES(4,CURRENT_TIMESTAMP,2500);

SELECT * FROM BANK_ACCOUNT
SELECT * FROM TRANSACTIONS